import { Inter, Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["100", "300"],
  variable: "--font-roboto",
});

const playfair_display_init = Playfair_Display({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-playfair_display",
});

export const metadata = {
  title: "OyuncuMarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto_init.className} ${playfair_display_init.className} bg-[#F0F0F0]`}
      >
        {children}
      </body>
    </html>
  );
}
